name: "Exemple de workflow"
on:
  push:
    branches:
      - main

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Say hello
      uses: ./ # Utilise l'action locale
      with:
        username: "Jean"
        greeting: "Salut"
